USE CONTROLE_FINANCAS;

CREATE TABLE Credential
(IdCredential INT CONSTRAINT PK_Credential PRIMARY KEY CLUSTERED IDENTITY(1,1) NOT NULL,
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL,
Active BIT NOT NULL,
CreationDate DATETIME NOT NULL,
ChangeDate DATETIME NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE ServicePlan
(IdPlan TINYINT CONSTRAINT PK_Plan PRIMARY KEY CLUSTERED NOT NULL,
Description VARCHAR(30) NOT NULL,
ValuePlan DECIMAL(6,2) NOT NULL,
Renewal SMALLINT NOT NULL,
Active BIT NOT NULL,
CreationDate DATETIME NOT NULL,
ChangeDate DATETIME NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Client
(IdClient INT CONSTRAINT PK_Client PRIMARY KEY CLUSTERED IDENTITY(1,1) NOT NULL,
IdCredential INT CONSTRAINT FK_Credential FOREIGN KEY REFERENCES Credential(IdCredential) NOT NULL,
Name VARCHAR(80) NOT NULL,
Email VARCHAR(80) NOT NULL,
Phone VARCHAR(11) NOT NULL,
CPF VARCHAR(11) NULL,
CNPJ VARCHAR(14) NULL,
Active BIT NOT NULL,
CreationDate DATETIME NOT NULL,
ChangeDate DATETIME NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Signature
(IdSignature INT CONSTRAINT PK_Signature PRIMARY KEY CLUSTERED IDENTITY(1,1) NOT NULL,
IdPlan TINYINT CONSTRAINT FK_Plan FOREIGN KEY REFERENCES ServicePlan(IdPlan) NOT NULL,
IdClient INT CONSTRAINT FK_Client_Signature FOREIGN KEY REFERENCES Client(IdClient) NOT NULL,
ExpirationDate DATE NULL,
Active BIT NOT NULL,
CreationDate DATETIME NOT NULL,
ChangeDate DATETIME NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Type
(IdType CHAR(1) CONSTRAINT PK_Type PRIMARY KEY CLUSTERED NOT NULL,
Description VARCHAR(10) NOT NULL,
Active BIT NOT NULL,
CreationDate DATETIME NOT NULL,
ChangeDate DATETIME NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Category
(IdCategory TINYINT CONSTRAINT PK_Category PRIMARY KEY CLUSTERED NOT NULL,
Description VARCHAR(30) NOT NULL,
Active BIT NOT NULL,
CreationDate DATETIME NOT NULL,
ChangeDate DATETIME NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Method
(IdMethod TINYINT CONSTRAINT PK_Method PRIMARY KEY CLUSTERED NOT NULL,
Description VARCHAR(30) NOT NULL,
Active BIT NOT NULL,
CreationDate DATETIME NOT NULL,
ChangeDate DATETIME NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE BillsPayRecieve
(IdBills INT CONSTRAINT PK_Bills PRIMARY KEY CLUSTERED IDENTITY(1,1) NOT NULL,
IdClient INT CONSTRAINT FK_Client_Bills FOREIGN KEY REFERENCES Client(IdClient) NOT NULL,
IdType CHAR(1) CONSTRAINT FK_Type FOREIGN KEY REFERENCES Type(IdType) NOT NULL,
IdCategory TINYINT CONSTRAINT FK_Category FOREIGN KEY REFERENCES Category(IdCategory) NOT NULL,
IdMethod TINYINT CONSTRAINT FK_Method FOREIGN KEY REFERENCES Method(IdMethod) NOT NULL,
Description VARCHAR(100) NOT NULL,
ValuePredicted DECIMAL(8,2) NOT NULL,
ValuePaidRecieved DECIMAL (8,2) NULL,
Recurrent BIT NOT NULL,
DueDate DATE NOT NULL,
SettlementDate DATE NULL,
Receipt VARCHAR(200) NOT NULL,
Active BIT NOT NULL,
CreationDate DATETIME NOT NULL,
ChangeDate DATETIME NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);
