USE CONTROLE_FINANCAS;

CREATE TABLE Credential
(IdCredential INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL,
Active BIT NOT NULL,
CreationDate DATE NOT NULL,
ChangeDate DATE NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE ServicePlan
(IdPlan TINYINT PRIMARY KEY NOT NULL,
Description VARCHAR(30) NOT NULL,
ValuePlan DECIMAL(6,2) NOT NULL,
Renewal SMALLINT NOT NULL,
Active BIT NOT NULL,
CreationDate DATE NOT NULL,
ChangeDate DATE NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Signature
(IdSignature INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdPlan TINYINT CONSTRAINT FK_Plan FOREIGN KEY REFERENCES ServicePlan(IdPlan) NOT NULL,
ExpirationDate DATE NULL,
Active BIT NOT NULL,
CreationDate DATE NOT NULL,
ChangeDate DATE NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Client
(IdClient INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdCredential INT CONSTRAINT FK_Credential FOREIGN KEY REFERENCES Credential(IdCredential) NOT NULL,
IdSignature INT CONSTRAINT FK_Signature FOREIGN KEY REFERENCES Signature(IdSignature) NOT NULL,
Name VARCHAR(80) NOT NULL,
Email VARCHAR(80) NOT NULL,
Phone VARCHAR(11) NOT NULL,
CPF VARCHAR(11) NULL,
CNPJ VARCHAR(14) NULL,
Active BIT NOT NULL,
CreationDate DATE NOT NULL,
ChangeDate DATE NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Type
(IdType CHAR(1) PRIMARY KEY NOT NULL,
Description VARCHAR(10) NOT NULL,
Active BIT NOT NULL,
CreationDate DATE NOT NULL,
ChangeDate DATE NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Origin
(IdOrigin TINYINT PRIMARY KEY NOT NULL,
Description VARCHAR(30) NOT NULL,
Active BIT NOT NULL,
CreationDate DATE NOT NULL,
ChangeDate DATE NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE Method
(IdMethod TINYINT PRIMARY KEY NOT NULL,
Description VARCHAR(30) NOT NULL,
Active BIT NOT NULL,
CreationDate DATE NOT NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeDate DATE NULL,
ChangeUser VARCHAR(50) NULL);

CREATE TABLE BillsPayRecieve
(IdBills INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdClient INT CONSTRAINT FK_Client FOREIGN KEY REFERENCES Client(IdClient) NOT NULL,
IdType CHAR(1) CONSTRAINT FK_Type FOREIGN KEY REFERENCES Type(IdType) NOT NULL,
IdOrigin TINYINT CONSTRAINT FK_Origin FOREIGN KEY REFERENCES Origin(IdOrigin) NOT NULL,
IdMethod TINYINT CONSTRAINT FK_Method FOREIGN KEY REFERENCES Method(IdMethod) NOT NULL,
Description VARCHAR(100) NOT NULL,
ValuePredicted DECIMAL(8,2) NOT NULL,
ValuePaidRecieved DECIMAL (8,2) NULL,
Recurrent BIT NOT NULL,
DueDate DATE NOT NULL,
SettlementDate DATE NULL,
Receipt VARCHAR(100) NOT NULL,
Active BIT NOT NULL,
CreationDate DATE NOT NULL,
ChangeDate DATE NULL,
CreationUser VARCHAR(50) NOT NULL,
ChangeUser VARCHAR(50) NULL);
