USE CONTROLE_FINANCAS;

DROP TABLE BillsPayRecieve;
DROP TABLE Type;
DROP TABLE Method;
DROP TABLE Category;
DROP TABLE Signature;
DROP TABLE ServicePlan;
DROP TABLE Client;
DROP TABLE Credential;

CREATE DATABASE CONTROLE_FINANCAS;